# Generated by Django 5.0.1 on 2024-02-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_desc', models.CharField(max_length=500, verbose_name='Descrição do produto')),
                ('pro_preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do produto')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Produtos_Das_Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdv_qtd', models.PositiveIntegerField(default=1, verbose_name='Quantidade comprada')),
                ('pdv_PrecoTotalItem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total do produto')),
                ('pdv_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.produto', verbose_name='Código do produto')),
            ],
            options={
                'verbose_name': 'Produtos da venda',
                'verbose_name_plural': 'Produtos das vendas',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ven_precoTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço total')),
                ('ven_DataHora', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora da compra')),
                ('ven_desc', models.CharField(max_length=1000, verbose_name='Descrição da venda')),
                ('ven_pro', models.ManyToManyField(through='API.Produtos_Das_Vendas', to='API.produto', verbose_name='Produtos da venda')),
            ],
            options={
                'verbose_name_plural': 'Vendas',
                'ordering': ['ven_DataHora'],
            },
        ),
        migrations.AddField(
            model_name='produtos_das_vendas',
            name='pdv_ven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.venda', verbose_name='Código da venda'),
        ),
    ]
