# Generated by Django 5.0.1 on 2024-02-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_produtos_das_vendas_pdv_precototalitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pro_preco',
            field=models.FloatField(verbose_name='Preço do produto'),
        ),
        migrations.AlterField(
            model_name='produtos_das_vendas',
            name='pdv_PrecoTotalItem',
            field=models.FloatField(default=0.0, verbose_name='Valor total do produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ven_precoTotal',
            field=models.FloatField(verbose_name='Preço total'),
        ),
    ]
