# Generated by Django 5.0.1 on 2024-02-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_produto_pro_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='ven_pago',
            field=models.CharField(choices=[('Pagou', 'Pagou'), ('Não pagou', 'Não Pagou')], default='Não pagou', max_length=10, verbose_name='Cliente pagou?'),
        ),
    ]
